# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4e9473fbc73e0163cd1d3187ab9c141f"
name = "autmazione-base-price"
application_url = "https://autmazione-base-price.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://autmazione-base-price.onrender.com/api/auth" ]
